# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.1
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: webscheduler
description: Emission scheduling web UI 📅
docs: true
docsurl: https://radio-aktywne.github.io/app-webscheduler
envprefix: WEBSCHEDULER
imagename: apps/webscheduler
keyprefix: webscheduler
port: 32000
registry: true
releases: true
reponame: app-webscheduler
repourl: https://github.com/radio-aktywne/app-webscheduler
